name: Check Branch Name Format

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check branch name
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF}
          if ! [[ "$BRANCH_NAME" =~ ^[a-z]+([A-Z][a-z0-9]+)*$ ]]; then
            echo "Branch name $BRANCH_NAME is not in camelCase format."
            exit 1
          else
            echo "Branch name $BRANCH_NAME is in camelCase format."
          fi
